### ISSUE TITLE
[JOSS review] Inconsistent version numbers

### ISSUE THREAD

**Issue by mefuller** [ORNL/Equilipy#1]
Hi,
As part of the JOSS review, I have noticed that the version installed with pip (and git tag) indicate version 0.1.3, but the setup.py in this tag and in main indicate v0.1.1
This inconsistency should be addressed, perhaps with a version bump in setup.py to v0.1.4, a corresponding tag, and updated build for pip to unify the value (on completion of review and corresponding updates, perhaps).

**Comment by SunyongKwon** [comment]
Thank you so much for checking the version number. As you requested, I matched all versions into v0.1.4.
