### ISSUE TITLE
[JOSS review] Examples - add recommends or edit

### ISSUE THREAD

**Issue by mefuller** [ORNL/Equilipy#3]
Example 3 requires the `fastexcel` package as currently provided.
It would be beneficial, but not critical, to add this as a recommended install under the example web documentation and/or rewrite the example to read from a csv or otherwise not require any additional packages

**Comment by lanari** [comment]
I noticed this problem too, and it would be good to add in the README that some examples require `fastexcel` and give the command `pip install fastexcel`.

**Comment by SunyongKwon** [comment]
Thank you so much for the feedback. I update the documentation for preinstalling `fastexcel`: please see `Depenancy to Polars` under `Preinstall` in web documentation (https://ornl.github.io/Equilipy/preinstall.html) and `Additional note` in README.md file.

Let me know if i can close this issue.
