### ISSUE TITLE
[JOSS review] Add and/or properly document tests

### ISSUE THREAD

**Issue by mefuller** [ORNL/Equilipy#4]
Documentation does not identify any test suite. Please add to documentation if it already exists. If not, package should have tests, preferably integrated into CI.

**Comment by SunyongKwon** [comment]
Hi @mefuller, thank you so much for the feedback. I completely agree with your comment. 

We integrated the test suite in `./test/` directory into our CI using the GitHub Actions. This test suite will ensure some core functions (`equilib_single', `equilib_batch`, and `scheil_cooling`) runs without raising errors. More rigorous tests will be added in the future along with the current test cases.

I added a brief description regarding the test suite in the Install section in our documentation.
